export const skillsMarqueeItems = [
  "AI/ML Engineering",
  "LLM Applications",
  "Retrieval-Augmented Generation (RAG)",
  "Entrepreneurship & AI Startups",
  "AI Agents & Agentic Workflows",
  "FastAPI & Backend Systems",
  "Cloud & Deployment Workflows",
  "Healthcare AI",
  "AI for Education",
  "Preventive Health Systems",
  "AI Infrastructure",
  "Open Source AI",
  "Voice AI Engineering",
  "Edge AI Systems",
  "Multi-Agent Systems",
  "Conversational AI",
] as const;
